
parameters:
  estimator_name: 'ab_b_hgb'
  target_field: reod
  id_field: ID
  # mode: calibration
  mode: submission
  test_size: 0.90
  # test_size: 0.33
  data_set_name: default
  features:
    - ID
    # - day
    # - equity
    - nbr_positif
    - nbr_negatif
    - perf
    - r_min
    - r_max
    # - r40
    # - r41
    # - r42
    # - r43
    # - r44
    - r45
    - r46
    - r47
    - r48
    - r49
    - r50
    - r51
    - r52
  estimator_names:
    - 'Dummy most_frequent'
    # - 'Dummy prior'
    # - 'Dummy stratified'
    # - 'Dummy uniform'
    # - 'Dummy constant'
    - 'Random Forest'
    # - 'Random Forest Calibrated'
    - 'Gradient Boosting - log_loss'
    # - 'Gradient Boosting - deviance'
    # - 'Gradient Boosting'
    - 'Gradient Boosting Calibrated'
    - 'Ada Boost'
    # - 'Ada Boost Calibrated'
    # - 'Bagging'
    # - 'Bagging - Extra Trees'
    # - 'Bagging - Random Forest'
    # - 'Bagging - Hist Gradient Boosting'
    # - 'Bagging Calibrated'
    # - 'Extra Trees'
    - 'Extra Trees Calibrated'
    # - 'Decision Tree'
    - 'Decision Tree Calibrated'
    # - 'Hist Gradient Boosting'
    - 'Hist Gradient Boosting - auto'
    # - 'Hist Gradient Boosting - categorical_crossentropy'
    - 'Hist Gradient Boosting Calibrated'
    # - 'MLP'
    - 'MLP Calibrated'
    # - 'AB_GB_HGB'
    # - 'Stacking 1'
    # - 'Stacking 2'
    # - 'Stacking 4'
    - 'Voting_ab_gb_hgb'
    - 'Stacking Ref'
  # 2023-03-11 11:09:52,781 - root- INFO - 0.48523657061543934      Random Forest in 0:13:23.226058
  # 2023-03-11 18:35:40,738 - root- INFO - 0.4972636360042977       Gradient Boosting in 7:25:47.956283
  # 2023-03-11 18:38:06,242 - root- INFO - 0.471355317673354        Ada Boost in 0:02:25.500785
  # 2023-03-11 20:54:13,962 - root- INFO - 0.4887293425180298       Extra Trees in 2:16:07.718478
  # 2023-03-11 20:55:09,602 - root- INFO - 0.40575085612438866      Decision Tree in 0:00:55.639751
  # 2023-03-11 20:55:27,772 - root- INFO - 0.5277355554836878       Hist Gradient Boosting in 0:00:18.168397
  # 2023-03-11 20:57:36,318 - root- INFO - 0.41186680034065304      MLP in 0:02:08.545308