root_folder: './'
# root_folder: '/content/drive/MyDrive/Kaggle/kaggle-competitions/'
parameters:
  estimator_name: 'ab_b_et_rf_hgb_dt_mlp_x'
  mode: calibration
  # mode: submission
  test_size: 0.33
  estimator_names:
    - 'Dummy most_frequent'
    # - 'Dummy prior'
    # - 'Dummy stratified'
    # - 'Dummy uniform'
    # - 'Dummy constant'
    - 'Random Forest'
    # - 'Random Forest Calibrated'
    # - 'Gradient Boosting - log_loss'
    # - 'Gradient Boosting - deviance'
    # - 'Gradient Boosting'
    # - 'Gradient Boosting Calibrated'
    # - 'Ada Boost'
    # - 'Ada Boost Calibrated'
    # - 'Bagging'
    # - 'Bagging - Extra Trees'
    # - 'Bagging - Random Forest'
    # - 'Bagging - Hist Gradient Boosting'
    # - 'Bagging Calibrated'
    # - 'Extra Trees'
    # - 'Extra Trees Calibrated'
    # - 'Decision Tree'
    # - 'Decision Tree Calibrated'
    - 'Hist Gradient Boosting'
    # - 'Hist Gradient Boosting - auto'
    # - 'Hist Gradient Boosting Calibrated'
    # - 'Hist Gradient Boosting Calibrated - auto'
    # - 'MLP'
    # - 'MLP Calibrated'
    # - 'KNeighbors'
    # - 'AB_GB_HGB'
    # - 'gb_ab_b_et_rf_hgb_dt_mlp'
    # - 'Ref_ab_b_et_rf_hgb_dt_mlp'
    # - gb_b_et_rf_hgb
    # - ab_b_et_rf_hgb_dt_mlp
    # - b_et_rf_hgb_dt_mlp
    # - et_rf_hgb_dt_mlp
    # - rf_hgb_dt_mlp
    # - hgb_dt_mlp
    # - relu
    # - sigmoid
    # - softmax
    # - softplus
    # - softsign
    # - tanh
    # - selu
    # - elu
